#Stage 1 - Build the Angular App
FROM node:14 as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

#Stage 2 - Serve the angular app using nginx
FROM nginx:alpine
COPY --from=node /app/dist/twitter-insights /usr/share/nginx/html 

